### ISSUE TITLE
java.lang.RuntimeException: could not find requested vehicle 113ecc in simulation for agent

### ISSUE THREAD

**Issue by Mengzhuoxiao** [eqasim-org/matsim-sharing#5]
Hi there,

I added a sharing car service but not really underlying mode "car" in order to distinguish the score parameters from sharing service and private car. What I did is first  add a new network mode called "scar", and then link it to the sharing service in the sharing service config group.

However a runTimeException is thrown here:

java.lang.RuntimeException: could not find requested vehicle 113ecc in simulation for agent BasicPlanAgentImpl{plan=[score=29.086211440912123][nof_acts_legs=33][type=null][personId=113ecc], vehicle=null, state=LEG, currentPlanElementIndex=5, currentLinkId=261715230005f} with id 113ecc on link 261715230005f at time 32760.0. aborting ...
	at org.matsim.core.mobsim.qsim.qnetsimengine.VehicularDepartureHandler.handleCarDeparture(VehicularDepartureHandler.java:83) ~[matsim-13.0.jar:?]
	at org.matsim.core.mobsim.qsim.qnetsimengine.VehicularDepartureHandler.handleDeparture(VehicularDepartureHandler.java:56) ~[matsim-13.0.jar:?]
	at org.matsim.core.mobsim.qsim.QSim.arrangeAgentDeparture(QSim.java:486) ~[matsim-13.0.jar:?]
	at org.matsim.core.mobsim.qsim.QSim.arrangeNextAgentAction(QSim.java:448) ~[matsim-13.0.jar:?]
	at org.matsim.core.mobsim.qsim.QSim$1.arrangeNextAgentState(QSim.java:149) ~[matsim-13.0.jar:?]
	at org.matsim.core.mobsim.qsim.ActivityEngineDefaultImpl.doSimStep(ActivityEngineDefaultImpl.java:108) ~[matsim-13.0.jar:?]
	at org.matsim.core.mobsim.qsim.QSim.doSimStep(QSim.java:395) ~[matsim-13.0.jar:?]
......................

Somehow the route from pickup activity to dropoff activity does not have a vehicle id. In this case matsim will match person id as the vehicle id. see BasicPlanAgentImpl.getPlannedVehicleId

However, the corresponding parkedVehicles in AbstractQLink is personId + "_scar" now since scar is the corresponding network mode. So when qlink.removeParkedVehicle(vehicleId) is called, the runTimeException above will be thrown out.

Any suggestions here? Thanks in advance and really appreciate for your efforts!

**Comment by tschlenther** [comment]
might actually a "MATSim" issue rather than a matsim-sharing issue. I just looked into the NetworkInclAccessEgressRoutingModule and it indeed does not set the vehicleId in the route, despite the fact that it actually looks up the vehicle in the scenario and passes it to the router... So i'll try and fix that over there and this will hopefully enable to use sharing with other underlying modes than car.

**Comment by Mengzhuoxiao** [comment]
It is fixed, just as what @tschlenther suggested.
